
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Providers from "./Providers";
import "./globals.css";
const inter = Inter({ subsets: ['latin'], display: 'swap' });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${inter.className}`}>

        
        <Providers>
        {children}
        </Providers>
       
      </body>
    </html>
  );
}
